# Generated by Django 5.1.1 on 2024-10-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='day',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='day',
            name='meal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='day',
            name='mode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='day',
            name='service',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='dates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='agent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='file_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='flight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='validity',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='quotationslab',
            name='max_pax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotationslab',
            name='min_pax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotationslab',
            name='no_of_foc',
            field=models.IntegerField(),
        ),
    ]
