# Generated by Django 5.1.1 on 2024-10-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_city_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
